### ISSUE TITLE
FFI::NullPointerError: invalid memory read at address

### ISSUE THREAD

**Issue by hamin** [postmodern/ffi-hunspell#1]
Hi,

I'm running into a weird null pointer error when using a custom dictionary. Here's how I'm able to recreate it:

foo.dic

<pre>
2
apple
orange
</pre>

Then trying to do something like this, I get the null pointer error:

<pre>
dict = FFI::Hunspell::Dictionary.new("foo.aff","foo.dic")
dict.suggest("logically") # => FFI::NullPointerError: invalid memory read at address=0x00000000000000
</pre>

Any ideas to what's going on here? Btw I'm using ruby 1.9.2 on os x 10.6

**Comment by postmodern** [comment]
This should be fixed in c7cfb16c25e9c78ecaf2b006aca871e0a0847d2f where a `count > 0` check was added, which should indicate the pointer has been written to.
