### ISSUE TITLE
Problem after compilation on Mac

### ISSUE THREAD

**Issue by raouiyounes** [postmodern/ffi-hunspell#13]
Hi,

After upgrading my Mac OS, I want to compile a program of Opencv, but I get this error : 
`Referenced from: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
  Expected in: /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
 in /System/Library`

What should I do ?

**Comment by postmodern** [comment]
Uh, I think you may have submitted this bug to the wrong repository. ffi-hunspell are Ruby FFI bindings to the hunspell spell-checking library.
