### ISSUE TITLE
Usage with a paragraph of text?

### ISSUE THREAD

**Issue by oyeanuj** [postmodern/ffi-hunspell#21]
Hi @postmodern, firstly, thank you for creating this library. I was curious if there was any example of using it with a paragraph of text? Or is it only meant to be used one word at a time and get suggestions for that word?

Is there a performant way to feed in a paragraph, and get a hash of the problem-word, its offset, and its suggestions?

Thank you!

**Comment by postmodern** [comment]
I believe you have to lex the paragraph yourself and run each word against the dictionary. Probably something like `str.split(/\W+/).each_with_index { |word,index| ... }`.
