### ISSUE TITLE
Cannot find dictionary

### ISSUE THREAD

**Issue by jackkinsella** [postmodern/ffi-hunspell#3]
Hey,

Looking forward to adding your gem to my app, but I'm running into trouble running it on a mac. How do you install dictionaries? Is there a particular format I should be looking for? I'm new to the NLP world so sorry if these are newbie questions.

> > FFI::Hunspell.dict('en_GB') {|d| d.check? "dog"}
> > RuntimeError: unable to find the dictionary "en_GB" in any of the directories

Kind Regards,
Jack

**Comment by ninjarabbi** [comment]
I just installed the gem (on a mac) and it's still unclear what I need to do to get the basic english dictionary. If I have to download a separate file and put it somewhere, how would that work in a production environment? Or something like Heroku, where you don't have direct access to the file system?
