### ISSUE TITLE
Prevent Memory Leak

### ISSUE THREAD

**Issue by ebenoist** [postmodern/ffi-hunspell#9]
There is a memory leak, which I am sure you aware of, when a new Dictionary object is created without being closed. I have some [spike code](https://github.com/ebenoist/ffi-hunspell/compare/memory-leak?expand=1) that uses a [finalizer](http://www.ruby-doc.org/core-2.1.3/ObjectSpace.html) to prevent this easy mistake.

I would want to clean it up, test it, and do a performance regression before putting up a PR, but wanted to see if you'd be interested in making this kind of enhancement first.

**Comment by postmodern** [comment]
I may have fixed another memory leak in `Dictionary#stem` and `Dictionary#suggest` where `Hunspell_free_list` wasn't being called on the `char **` returned by `Hunspell_stem` and `Hunspell_suggest`. ab0c6a36f7d5078f138bb5c4a211920ab6e45b2a

As for this issue with closing the dictionary pointer, maybe we could use [FFI::AutoPointer](https://www.rubydoc.info/github/ffi/ffi/FFI/AutoPointer)?

**Comment by postmodern** [comment]
See the [auto_pointer](https://github.com/postmodern/ffi-hunspell/tree/auto_pointer) branch and 530c548a12d7c4bed300faed18275523e3b6f121.

**Comment by postmodern** [comment]
Merged into master and released 0.6.1. If there's still memory leaks detected, re-open this issue with fresh analysis.
